### ISSUE TITLE
"null" value in company field

### ISSUE THREAD

**Issue by nikodg** [csii-org/time-service#1]
Please check /employees and /employeeTimes API response

**Comment by analynf** [comment]
![image](https://user-images.githubusercontent.com/12998868/41548192-c23e2a64-7354-11e8-9150-c5e002586bb8.png)

**Comment by analynf** [comment]
![image](https://user-images.githubusercontent.com/12998868/41548299-1deb5d32-7355-11e8-80a8-992b5066627b.png)

**Comment by analynf** [comment]
There is a company field in the response. Please check again.

**Comment by nikodg** [comment]
This is fixed
